'use strict';

const NOT_FOUND = 404;
const NO_CONTENT = 204;
const UNPROCESSABLE_CONTENT = 422;
const BAD_REQUEST = 400;
const CREATED = 201;

module.exports = {
  NOT_FOUND,
  NO_CONTENT,
  UNPROCESSABLE_CONTENT,
  BAD_REQUEST,
  CREATED,
};
