'use strict';

const SUCCESSFUL_OK = 200;
const SUCCESSFUL_CREATED = 201;
const SUCCESSFUL_NO_CONTENT = 204;
const ERROR_BAD_REQUEST = 400;
const ERROR_NOT_FOUND = 404;
const ERROR_UNPROCESSABLE_ENTITY = 422;

module.exports = {
  SUCCESSFUL_OK,
  SUCCESSFUL_CREATED,
  SUCCESSFUL_NO_CONTENT,
  ERROR_BAD_REQUEST,
  ERROR_NOT_FOUND,
  ERROR_UNPROCESSABLE_ENTITY,
};
